<?php
// var_dump($data_pp);exit();
?>

<head>
    <style type="text/css">
        /*body{
      padding-top:1000px;
      margin-top:1000px;
    }*/
        h4 {
            font-size: 14px;
        }

        table tr td {
            font-size: 10px;
        }

        .center {
            display: block;
            margin-left: auto;
            margin-right: auto;
            /*width: 50%;*/
        }

        .singleborder {
            border-collapse: collapse;
            border: 1px solid black;
        }

        .notopborder {
            border-collapse: collapse;
            border: 1px solid black;
            border-top: 0px solid black;
        }

        .nobottomborder {
            border-collapse: collapse;
            border: 1px solid black;
            border-bottom: 0px solid black;
        }

        body {
            font-size: 10px;
        }
    </style>
    <title>Permohonan Pembayaran</title>
</head>

<body>
    <h3 style="text-align: center;">PERMOHONAN PEMBAYARAN</h3>
    <table class="singleborder" border="0" width="100%">
        <tr>
            <td width="13%">Nomor PP</td>
            <td width="2%">:</td>
            <td align="left"><?= $data_pp->ref_pp; ?></td>
            <td width="25%">Tanggal : <?= date("d-m-Y"); ?></td>
        </tr>
        <tr class="notopborder">
            <td>Nomor Order</td>
            <td>:</td>
            <td><?= $data_pp->ref_po; ?></td>
            <td></td>
        </tr>
        <tr>
            <td>Supplier</td>
            <td>:</td>
            <td colspan="2"><?= $data_pp->kode_supplytxt . " / " . $data_pp->nama_supply; ?></td>
        </tr>
        <tr>
            <td>Kepada</td>
            <td>:</td>
            <td colspan="2"><?= $data_pp->nama_supply; ?></td>
        </tr>
        <tr>
            <td>Jumlah</td>
            <td>:</td>
            <td colspan="2">Rp <?= number_format($data_pp->jumlah, 2); ?></td>
        </tr>
        <tr>
            <td>Terbilang</td>
            <td>:</td>
            <td><?= $data_pp->terbilang; ?></td>
            <td class="nobottomborder" valign="top" rowspan="2">
                Bank &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : (&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;) <br />
                Cash &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : (&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;) <br />
                Cheque/Giro : (&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)
            </td>
        </tr>
        <tr>
            <td valign="top">Keterangan</td>
            <td valign="top">:</td>
            <td valign="top"><?= $data_pp->ket; ?></td>
        </tr>
    </table>
    <table class="notopborder" border="0" width="100%">
        <tr>
            <td align="center" valign="top" height="90">Disetujui Oleh</td>
            <td align="center" valign="top" height="90">Pemohon</td>
            <td align="center" valign="top" height="90">Dibayar Oleh</td>
            <td align="center" valign="top" height="90">Diterima Oleh</td>
        </tr>
        <tr>
            <td align="center">(___________________)</td>
            <td align="center">(___________________)</td>
            <td align="center">(___________________)</td>
            <td align="center">(___________________)</td>
        </tr>
    </table>
    <small><i>User Sistem : <?= $this->session->userdata('user'); ?></i></small> <br />
    <small><i>Tgl Cetak <?= date("d/m/Y H:i:s"); ?> - Client <?= $this->input->ip_address(); ?> <?= $this->platform->agent(); ?></i></small><br />
    <small>Print generated by MMOP Website</small>
</body>