<?php
// var_dump($bpb);exit();
?>

<head>
    <style type="text/css">
        /*body{
      padding-top:1000px;
      margin-top:1000px;
    }*/
        h4 {
            font-size: 14px;
        }

        table tr td {
            font-size: 10px;
        }

        .center {
            display: block;
            margin-left: auto;
            margin-right: auto;
            /*width: 50%;*/
        }

        .singleborder {
            border-collapse: collapse;
            border: 1px solid black;
        }

        body {
            font-size: 10px;
        }
    </style>
    <title>Bon Permintaan Barang</title>
</head>

<body>
    <table border="0" width="100%">
        <tr>
            <td rowspan="2" width="12%"><img width="10%" height="10%" src="./assets/qrcode/bpb/<?php echo $id . "_" . $no_bpb; ?>.png"></td>
            <td align="center" valign="bottom">
                <h4 align="center" style="margin: 0px;padding: 0px;">BON PERMINTAAN BARANG</h4>
            </td>
        </tr>
        <tr>
            <td align="center" valign="baseline">
                <h5 align="center" style="margin: 0px;padding: 0px 0px 10px 0px;"><b>No. BPB : <?= $bpb->nobpb; ?> <br /> No. Ref BPB : <?= $bpb->norefbpb; ?></b></h5>
            </td>
        </tr>
    </table>
    <table width="100%">
        <tr>
            <!-- <td>Depart/Divisi : <?= $bpb->bag; ?></td> -->
            <!-- <td align="right">Tanggal : <?= $bpb->tgl; ?></td> -->
        </tr>
    </table>
    <table class="singleborder" border="1" width="100%">
        <tr>
            <td align="center">No</td>
            <td align="center">No. Kode Barang</td>
            <td align="center">Nama / Spesifikasi Barang</td>
            <td align="center">Sat</td>
            <td align="center">Jml Diminta</td>
            <td align="center">Keterangan</td>
        </tr>
        <?php
        $no = 1;
        foreach ($bpbitem as $listbpbitem) {
        ?>
            <tr>
                <td><?= $no ?></td>
                <td><?= $listbpbitem->kodebar; ?></td>
                <td><?= $listbpbitem->nabar; ?></td>
                <td><?= $listbpbitem->satuan; ?></td>
                <td><?= $listbpbitem->qty; ?></td>
                <td><?= $listbpbitem->ket; ?></td>
            </tr>
        <?php } ?>
        <tr>
            <td colspan="2">
                Distribusi :<br />
                -Ke 1 - Kantor Kebun/PKS<br />
                -Ke 2 - Gudang
            </td>
            <td colspan="4">
                <table border="0" width="100%">
                    <tr>
                        <!-- <td align="center">Diminta Oleh,</td> -->
                        <!-- <td align="center">Dibukukan,</td> -->
                        <td align="center">Diajukan oleh,</td>
                        <td align="center">Diperiksa,</td>
                        <td align="center">Diterima oleh,</td>
                    </tr>
                    <tr>
                        <td colspan="4" height="50"></td>
                    </tr>
                    <tr>
                        <!-- <td align="center">(___________________)</td> -->
                        <td align="center">(___________________)</td>
                        <td align="center">(___________________)</td>
                        <td align="center">(___________________)</td>
                    </tr>
                    <tr>
                        <td align="center"><?= $bpb->user; ?></td>
                        <td align="center">KTU</td>
                        <!-- <td align="center">Kasie Gudang</td> -->
                        <td align="center"></td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
    <small><i>Tgl Cetak <?= date("d/m/Y H:i:s"); ?> - Client <?= $this->input->ip_address(); ?> <?= $this->platform->agent(); ?></i></small><br />
    <small>Print generated by MMOP Website</small>
</body>